### ISSUE TITLE
"Unable to determine which project file to add the reference to" errors

### ISSUE THREAD

**Issue by ardalis** [ardalis/modulith#24]
Looks like it *mostly* worked but we shouldn't be getting failures in the basic workflow of the modulith to create and add modules to a new empty solution.

![image](https://github.com/david-acm/modulith/assets/782127/b0e638ff-7185-4587-8d65-bb8ab60a8572)

**Comment by david-acm** [comment]
So these errors will appear when any .Net SDK below 9.0.100-preview.6.x. The reason is that one of the post actions tries to add the project references to existing projects. Starting with 9.0.100-preview.6.x a change has been made to allow these references.

Should I change the error description to make it more explanatory? So you have suggestions for that message?

**Comment by ardalis** [comment]
It should probably be made really clear that this (this whole package and templates) only really works with dotnet 9 preview 6, then. Which won't be a big issue in 2 months.

**Comment by david-acm** [comment]
@ardalis Created #51 addressing this issue. The pr adds a note to the top of the readme and adds the manual command the user needs to run when using .Net 8:

```
Unable to determine which project file to add the reference to.
Post action failed.
Manual instructions: 
⚠️ This is only supported in .Net SDK 9.0.100-preview.7 and newer.
🔧 For earlier versions please run:

        dotnet add eShop.Web/eShop.Web.csproj reference Billing/eShop.Billing/eShop.Billing.csproj

Unable to determine which project file to add the reference to.
Post action failed.
Manual instructions: 
⚠️ This is only supported in .Net SDK 9.0.100-preview.7 and newer.
🔧 For earlier versions please run:

        dotnet add Billing/eShop.Billing/eShop.Billing.csproj reference Shared/eShop.SharedKernel/eShop.SharedKernel.csproj
```

**Comment by ardalis** [comment]
Sounds great, closing.
