### ISSUE TITLE
Add nuget key to this repo config for CD pipelines

### ISSUE THREAD

**Issue by david-acm** [ardalis/modulith#27]
As a repo contributor I want to be able to publish new versions to Ardalis.Modulith nuget feed.

**Comment by ardalis** [comment]
Should I keep the NuGet Package name Productive.Modulith or make it Ardalis.Modulith so people searching nuget for "ardalis" discover it?

**Comment by ardalis** [comment]
I need an answer to the above question before I can create the key and publish.

**Comment by david-acm** [comment]
Let's name it Ardalis.Modulith

**Comment by ardalis** [comment]
Finally done and a package is available here:
https://www.nuget.org/packages/Ardalis.Modulith/

@david-acm I'm ready to start contributing more to this if you want to get your PR to a mergeable state when you have a chance. Thanks!
