### ISSUE TITLE
Issue with x.* versions

### ISSUE THREAD

**Issue by ardalis** [ardalis/modulith#39]
Getting NU1100 errors for all package references that use *:

Unable to resolve 'FastEndpoints (>= 5.0.0)' for 'net8.0'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, LocalNuget, Microsoft Visual Studio Offline Packages, nuget.org.
Unable to resolve 'mediatr (>= 12.0.0)' for 'net8.0'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, LocalNuget, Microsoft Visual Studio Offline Packages, nuget.org.
Unable to resolve 'MudBlazor (>= 7.0.0)' for 'net8.0'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, LocalNuget, Microsoft Visual Studio Offline Packages, nuget.org.
Unable to resolve 'tngtech.archunitnet.xunit (>= 0.10.0)' for 'net8.0'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, LocalNuget, Microsoft Visual Studio Offline Packages, nuget.org.
Unable to resolve 'xunit (>= 2.0.0)' for 'net8.0'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, LocalNuget, Microsoft Visual Studio Offline Packages, nuget.org.
Unable to resolve 'coverlet.collector (>= 6.0.0)' for 'net8.0'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, LocalNuget, Microsoft Visual Studio Offline Packages, nuget.org.
Unable to resolve 'FastEndpoints (>= 5.0.0)' for 'net8.0'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, LocalNuget, Microsoft Visual Studio Offline Packages, nuget.org.
Unable to resolve 'mediatr (>= 12.0.0)' for 'net8.0'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, LocalNuget, Microsoft Visual Studio Offline Packages, nuget.org.
Unable to resolve 'MudBlazor (>= 7.0.0)' for 'net8.0'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, LocalNuget, Microsoft Visual Studio Offline Packages, nuget.org.
Unable to resolve 'MudBlazor (>= 7.0.0)' for 'net8.0/browser-wasm'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, LocalNuget, Microsoft Visual Studio Offline Packages, nuget.org.
Unable to resolve 'FastEndpoints.Security (>= 5.0.0)' for 'net8.0'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, LocalNuget, Microsoft Visual Studio Offline Packages, nuget.org.
Unable to resolve 'FastEndpoints (>= 5.0.0)' for 'net8.0'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, LocalNuget, Microsoft Visual Studio Offline Packages, nuget.org.
Unable to resolve 'FastEndpoints.Swagger (>= 5.0.0)' for 'net8.0'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, LocalNuget, Microsoft Visual Studio Offline Packages, nuget.org.
Unable to resolve 'MudBlazor (>= 7.0.0)' for 'net8.0'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, LocalNuget, Microsoft Visual Studio Offline Packages, nuget.org.
Unable to resolve 'mediatr (>= 12.0.0)' for 'net8.0'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, LocalNuget, Microsoft Visual Studio Offline Packages, nuget.org.

**Comment by david-acm** [comment]
Hey @ardalis I'm looking into this. What version of the template and .Net SDK are you using? Also, could you share the cli commands you used to instantiate the template that produced those errors?

**Comment by david-acm** [comment]
Looking at the error message the issue is caused by the ```PackageSourceMapping``` configuration which discards nuget.org as a source in that environment. If the package is not present in any of the mapped configured packages the restore will fail. 
- A workaround is to specify the specific versions that are present in the nuget sources of that particular environment.
- Or I could reverse the change specifying a wildcard for the minor versions. The downside to this is that newer minor versions and patches will need to be updated from time to time manually to allow new template instantiations with  updated updated.

**Comment by ardalis** [comment]
>  dotnet --version
> 9.0.100-preview.7.24407.12

I'd just freshly installed the templates.

**Comment by ardalis** [comment]
It's probably better for the templates to work consistently (and maybe require a manual nuget update afterward) than for them to not work at all (but be "up to date").

Also if there's a way to support Directory.Packages.props out of the box with the templates that would be ideal. Probably worth a separate issue for that if there isn't already one.

**Comment by ardalis** [comment]
I figured out the issue here - it's a sourcemapping problem not something with the project (helps if I read the error message)...

If fixed my issues with SourceMapping and now everything here:
https://github.com/ardalis/modulith/blob/main/Test-UiWithDotnetCli.ps1

works fine on my machine. :)
