### ISSUE TITLE
ArchUnitNET test should exclude EF Core Migrations

### ISSUE THREAD

**Issue by lloydkevin** [ardalis/modulith#60]
EF generates public classes for migrations and the snapshots.

e.g.:
![image](https://github.com/user-attachments/assets/f987ca3b-6f61-4139-8d8d-9b402fc317dd)

and

![image](https://github.com/user-attachments/assets/88324da4-fa2f-46c8-8aa2-ed3f961b4930)

**Comment by david-acm** [comment]
I'm going to guess that EF doesn't allow for these to be internal, right? It makes sense. in V2.0.0 I'm planning to add a feature slice that includes a repo with a sqlite db to the initial template, so I'll address this as part that version

**Comment by lloydkevin** [comment]
That's correct, when you run the dotnet command it generals public classes.

Can we add this, in the interim?

![image](https://github.com/user-attachments/assets/c91b84b9-820e-448c-be1c-d05371d0f620)

Or maybe exclude the classes the inherit from `Migration` and `ModelSnapshot`
